<?php

/**
 * @file
 * Contains rest_is_logged_in.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_help().
 */
function rest_is_logged_in_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rest_is_logged_in module.
    case 'help.page.rest_is_logged_in':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Rest is logged in resource') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rest_is_logged_in_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_ENTITY_TYPE_create_access().
 *
 * We want to allow creation of user entities for anonymous users.
 */
function rest_is_logged_in_user_create_access(\Drupal\Core\Session\AccountInterface $account, array $context, $entity_bundle) {
  return AccessResult::allowed();
}

/**
 * Implements hook_entity_field_access().
 *
 * @todo: Both this one and the next should probably be in another module. But
 * since I had this file open... YOLO.
 */
function rest_is_logged_in_entity_field_access($operation, \Drupal\Core\Field\FieldDefinitionInterface $field_definition, \Drupal\Core\Session\AccountInterface $account, \Drupal\Core\Field\FieldItemListInterface $items = NULL) {
  if ($items && $items->getName() == 'status') {
    return AccessResult::allowed();
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_entity_field_access_alter().
 */
function rest_is_logged_in_entity_field_access_alter(array &$grants, array $context) {
  /* @var \Drupal\Core\Field\FieldItemListInterface $items */
  $items = $context['items'];
  if ($items && $items->getName() == 'status') {
    unset($grants[':default']);
  }
}